image: docker:stable

stages:
    - Build e Push image
    - Documentation

before_script:
    - apk add bash
    - echo "Read Environment Variable from .env file"
    - source ./.env
    - export JOB_ALPINE_RELEASE=${CI_ALPINE_RELEASE:-"$ALPINE_RELEASE"}

update readme:
    stage: Documentation
    variables:
        DOCKERHUB_USERNAME: "$DOCKER_HUB_USER"
        DOCKERHUB_PASSWORD: "$DOCKER_HUB_PASSWORD"
        DOCKERHUB_REPO_PREFIX: "maurosoft1973"
        DOCKERHUB_REPO_NAME: "alpine-php-fpm"
        DOCKERHUB_SHORT_DESCRIPTION: "PHP-FPM Docker image running on Alpine Linux"
    only:
        - master
    script:
        - LATEST_UPDATE=$(date +"%d.%m.%Y %H:%M:%S")
        - echo "Generate README for Version ${PHP_VERSION}"
        - sed "s/\%ALPINE_VERSION\%/${ALPINE_VERSION}/g" README.tpl > README.md1
        - sed "s/\%ALPINE_VERSION_DATE\%/${ALPINE_VERSION_DATE}/g" README.md1 > README.md2
        - sed "s/\%PHP_VERSION\%/${PHP_VERSION}/g" README.md2 > README.md3
        - sed "s/\%PHP_VERSION_DATE\%/${PHP_VERSION_DATE}/g" README.md3 > README.md4
        - sed "s/\%LATEST_UPDATE\%/${LATEST_UPDATE}/g" README.md4 > README.md
        - FULL_DESCRIPTION=$(if [ -f "$(pwd)/README.md" ]; then cat "$(pwd)/README.md"; else echo ""; fi)
        - docker pull maurosoft1973/alpine-readme-to-dockerhub
        - docker run --rm -e DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" -e DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" -e DOCKERHUB_REPO_PREFIX="$DOCKERHUB_REPO_PREFIX" -e DOCKERHUB_REPO_NAME="$DOCKERHUB_REPO_NAME" -e SHORT_DESCRIPTION="$DOCKERHUB_SHORT_DESCRIPTION" -e FULL_DESCRIPTION="$FULL_DESCRIPTION" maurosoft1973/alpine-readme-to-dockerhub

amd64 test build:
    image: docker
    stage: Build e Push image
    only:
        - master
    variables:
        RELEASE: "TEST"
    script:
        - bash ./build-image.sh -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -ar=$JOB_ALPINE_RELEASE -r=$RELEASE

amd64 current build:
    stage: Build e Push image
    variables:
        RELEASE: "CURRENT"
    only:
        - master
    script:
        - bash ./build-image.sh -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -ar=$JOB_ALPINE_RELEASE -r=$RELEASE

amd64 latest build:
    stage: Build e Push image
    variables:
        RELEASE: "LATEST"
    only:
        - master
    script:
        - bash ./build-image.sh -av=$ALPINE_VERSION -avd=$ALPINE_VERSION_DATE -ar=$JOB_ALPINE_RELEASE -r=$RELEASE



amd64 build latest:
  stage: Build e Push image
  only:
  - master
  script:
  - BUILD_DATE=$(date +"%Y-%m-%d")
  - docker build --build-arg BUILD_DATE=$BUILD_DATE -t maurosoft1973/alpine-php-fpm -t maurosoft1973/alpine-php-fpm:amd64 -t maurosoft1973/alpine-php-fpm:x86_64 .
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  - docker push maurosoft1973/alpine-php-fpm:amd64
  - docker push maurosoft1973/alpine-php-fpm:x86_64
  - docker push maurosoft1973/alpine-php-fpm

amd64 build 7.4.16:
  stage: Build e Push image
  only:
  - master
  script:
  - BUILD_DATE=$(date +"%Y-%m-%d")
  - docker build --build-arg BUILD_DATE=$BUILD_DATE -t maurosoft1973/alpine-php-fpm:7.4.16 -t maurosoft1973/alpine-php-fpm:7.4.16-amd64 -t maurosoft1973/alpine-php-fpm:7.4.16-x86_64 .
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  - docker push maurosoft1973/alpine-php-fpm:7.4.16-amd64
  - docker push maurosoft1973/alpine-php-fpm:7.4.16-x86_64
  - docker push maurosoft1973/alpine-php-fpm:7.4.16
